### ISSUE TITLE
updating command list

### ISSUE THREAD

**Issue by Qwyntex** [Qwyntex/doubleshift#12]
- [ ] update commands list when plugin state is changed

**Comment by tobloef** [comment]
Yes, please! In the meantime, it might be a good idea to add a disclaimer to the README. It took me a while to realize that I had to re-install the plugin to get the "Open better command palette" command to show up in doubleshift.

**Comment by ChrisFiftyTwo** [comment]
Would love to see this as well. Was unable to populate the list with new entries until I re-installed.

**Comment by Qwyntex** [comment]
I will do it (implement the feature) as soon as I have time again. But please do not reinstall the plugin. Just disable and enable it or reload/restart obsidian ( `Ctrl + R` I think. Otherwise just search for it in the command palette)

**Comment by Qwyntex** [comment]
This issue is now fixed with the newest release.
