### ISSUE TITLE
Double Command Key on macOS

### ISSUE THREAD

**Issue by zcysxy** [Qwyntex/doubleshift#13]
Thanks for this plugin! I tried to map a command to the double `Cmd` shortcut but failed. I tried replacing `Shift` with `Command`, `Cmd`, `CMD`, `Mod`, but with no luck

**Comment by NomarCub** [comment]
Have you tried `Control`? See this: https://github.com/Qwyntex/doubleshift/issues/10#issuecomment-1210641650
This definitely should be documented.

**Comment by Qwyntex** [comment]
I am currently working on a better way to make it easier to set the key for a command as I don't like the current solution myself

**Comment by zcysxy** [comment]
> Have you tried `Control`? See this: [#10 (comment)](https://github.com/Qwyntex/doubleshift/issues/10#issuecomment-1210641650)
> This definitely should be documented.

`Control` doesn't work either 😢

**Comment by lilruffian** [comment]
Map with `Meta`

**Comment by zcysxy** [comment]
> Map with `Meta`

It worked!! A huge thank you @lilruffian !

**Comment by Qwyntex** [comment]
Hey, sorry for not responding. Glad it worked. You can expect a better way of selecting keys somewhat around new years eve :)
