### ISSUE TITLE
add Support from Obsidian 'Better Command Palette'

### ISSUE THREAD

**Issue by rr19-hub** [Qwyntex/doubleshift#14]
The addon is great, but only supports the official command-palette. I have replaced it with [https://github.com/AlexBieg/obsidian-better-command-palette](https://github.com/AlexBieg/obsidian-better-command-palette), unfortunately the addon does not work here.
But in line 176 the command could easily be replaced by
`this.command = "obsidian-better-command-palette:open-better-commmand-palette";`

It would be great if the addon would automatically execute this command if the official command-palette is not installed.

**Comment by Qwyntex** [comment]
Have you changed the command in the settings tab?

**Comment by rr19-hub** [comment]
No, i didn't find a setting there, i changed it in the main.js. But now, I see a data.json with:
```
{
  "delay": 360,
  "key": "Shift",
  "shortcuts": [
    {
      "command": "obsidian-better-command-palette:open-better-commmand-palette",
      "key": "Shift",
      "lastKeyUpTime": 0
    }
  ]
}
```
oh, now I see: the command can be changed via the settings. Sorry, I had overlooked... 🙈
