### ISSUE TITLE
all keys possible

### ISSUE THREAD

**Issue by Qwyntex** [Qwyntex/doubleshift#3]
make a dropdown to let other keys be used to activate individual commands

**Comment by FelipeRearden** [comment]
Hello @Qwyntex !!!!

First of all, I'm loving your plugin !!!!!

Thank you very much, I'm so happy to br able to use `SHIFT+SHIFT` to hit the command that I want 💙

I was about to open an FR than I saw this post from you ...

My FR would be to have an **adittional** hotkey for a different Obsidian command. 

- `SHIFT+SHIFT` = Open Settings
- `CRTL+SHIFT+SHIFT` = Open Command Palette
- `CMD+SHIFT+SHIFT` = Open Command 3
- `OPTION/ALT+SHIFT+SHIFT` = Open Command 4 

As you can see, my idea is to have more double shifts to open different commands. 

---

I don't if this is the idea of this Issue Post 🧐

If not, let me know if I can open another FR :)

Thanks for reading this!!!

Have a great day!!!!!!

**Comment by Qwyntex** [comment]
Feel free to open another issue for that as the idea of this one was that you can execute commands by pressing other modifier keys like alt twice. I like the idea and i will work on that

**Comment by FelipeRearden** [comment]
Thank you very much @Qwyntex !!!!!

I've created these two :)

- #5

- #6

Good luck and have a great day!!!!!

**Comment by Qwyntex** [comment]
just type the desired key in the text field and it will replace `Shift`. All keys that have characters like Shift or Tab need to have a capitalized first letter. e.g.: `Shift` and not `shift` nor `SHIFT`.
#### Feature list:
- type the key you want in the text field
- alternate keys are supported (e.g.: `[` and `{`)
- it differentiates between `a` and `A`
- Function row works (`F10` and such)
- Space is currently just ` ` might need a change later if wanted
