### ISSUE TITLE
Release tag and brat

### ISSUE THREAD

**Issue by Mara-Li** [Qwyntex/doubleshift#4]
Hello ! Thank you for this plugin. Funny to see this appear the day after i talk about this on discord.

There is a problem with the tag release : to make BRAT function, you need to the release number. You tagged your release as "stable", but it should be "1.7.0" to make BRAT work !

I dunno what about the release for the plugin community but i think it will be good to be BRAT compilant :)

**Comment by Qwyntex** [comment]
it is now 1.7.0; just out of curiosity how does BRAT work?

**Comment by Mara-Li** [comment]
I don't have any details, but you can take a look here : https://github.com/TfTHacker/obsidian42-brat
