### ISSUE TITLE
[Feature Request] Support Multiple Keys

### ISSUE THREAD

**Issue by FelipeRearden** [Qwyntex/doubleshift#5]
Hello @Qwyntex !!!!!

As we talk here #3 , I'd like to suggest more Keys to this amazing plugin !

- `CRTL+SHIFT+SHIFT`
- `CMD+SHIFT+SHIFT`
- `ALT/OPT+SHIFT+SHIFT`

Thanks for reading this!!!

Have a great day!!!!

**Comment by kalmir** [comment]
What about `SPACE`? Doublespace would be great :-)

**Comment by Qwyntex** [comment]
now possible #3

**Comment by FelipeRearden** [comment]
> now possible #3 

Thank you very much @Qwyntex !!!!

I was going to install from a clean installation using the Community Plugins and the message is `fail to install`

I think I know why ... we don't have a release for the new version `2.1.1`  :)

**Comment by Qwyntex** [comment]
i am currently creating it. just so we are on the same page: you can now create multiple shortcuts but you can not yet have something like `Alt + Shift + Shift`

**Comment by FelipeRearden** [comment]
Hum … let me ask one thing  before I reply to your question  :)

Can I have these two hotkeys?
- `SHIFT + SHIFT` -> Command Palette
- `Tab + Tab` -> Search All Files 

In my case I will build 5 to 6 hotkeys to multiples commands. That why I’m asking :)

**Comment by Qwyntex** [comment]
Yep that will work. Just type `Shift` in one field and select open Command Palette and type `Tab` in another and select Search all file for this one

**Comment by FelipeRearden** [comment]
> i am currently creating it. just so we are on the same page: you can now create multiple shortcuts but you can not yet have something like `Alt + Shift + Shift`

My idea about `Alt + Shift + Shift` `CRTL+SHIFT+SHIFT` and `CMD+SHIFT+SHIFT` is because it’s very comfortable to use these hotkeys with the left hand 

If is feasible from the code perspective, would be amazing to have these groups :)

**Comment by FelipeRearden** [comment]
> Yep that will work. Just type `Shift` in one field and select open Command Palette and type `Tab` in another and select Search all file for this one

Great Amazing !!!! 

I see the new release, let me install and I get back to you :)

**Comment by Qwyntex** [comment]
I will do that it is just not yet done. I wanted to support multiple shortcuts first.

**Comment by FelipeRearden** [comment]
Fantastic strategy :) 

One step at time . . .  and we get there :)

**Comment by FelipeRearden** [comment]
I have one important thing to share with about installing from the Community Page …..

The last public release of Obsidian is `0.14.5` and the public beta is `0.14.6` 

Looking at the manifest.json the MinApp version is `0.14.6`
- Thats why I cant install from the Community Page :)

In a few days or weeks this beta will be the current and we will be  able to install from the Community Page 
- I’m gonna do a manual install and change the manifest.json manually to test the multiple shortcuts and give feedback to you :)

**Comment by Qwyntex** [comment]
apparently there were a few security issues with the old version and I updated the plugin automatically. I must have forgotten that this is still in beta and didn't think about it much more. I will change that back for the release as the code should still work. Thanks for the notice

**Comment by FelipeRearden** [comment]
> apparently there were a few security issues with the old version and I updated the plugin automatically. I must have forgotten that this is still in beta and didn't think about it much more. I will change that back for the release as the code should still work. 

Okay :) 

> Thanks for the notice 

I'm happy to help :)

**Comment by FelipeRearden** [comment]
After the new release I'm gonna do these things:

- Give feedback to @Qwyntex about the installing and user experience
- Rename this Issue to emphasize Multiple Selections 
- Close this issue after rename
- Open a new Issue to talk about CRTL/CMD/ALT Modifiers

**Comment by FelipeRearden** [comment]
> apparently there were a few security issues with the old version and I updated the plugin automatically. I must have forgotten that this is still in beta and didn't think about it much more. I will change that back for the release as the code should still work. Thanks for the notice 

Just to let you know that version 0.14.6 is available to the public in this exactly moment.

Have a great day!!!!

**Comment by FelipeRearden** [comment]
Working perfect on Obsidian `0.14.6` :)
