### ISSUE TITLE
Unable to Change Settings or Add New Command Bindings

### ISSUE THREAD

**Issue by ghost** [Qwyntex/doubleshift#9]
**UPDATE:**

Due to *my* faulty thinking and lack of experimentation, I was completely correct about this issue, and let it be known that it is likely an issue with the core plugin "Command Palette":

> The only case where I have trouble is when I install the plugin [Better Command Palette](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Plugins/obsidian-better-command-palette). It doesn't matter if the alternative command palette is installed or even enabled. Your plugin still works fine. The only problem is when the core plugin "Command Palette" is disabled.

**My original report follows. The above is from my follow-up, after discovery of the true issue.**

---

Until a few weeks ago I was *madly* in love with this plugin. I still love it, but the romance took a nasty spill when I tried to change the settings and add a new command and associated hotkey for it about 12 days ago.

Currently, even after reinstalling the plugin, deleting the plugin data or adding the plugin to a completely clean install of Obsidian and a completely new vault with no modified settings, when you go to Doubleshift's plugin settings page, the hotkey for the Command Palette command (the default, single command the plugin ships with, which is bound to double `SHIFT`, of course) doesn't show, and is unable to be changed. Where the hotkey should be shown, there is only a small blank rectangle, which does nothing upon clicking it.

It is also not possible to create any new bindings or modify any that already exist. The original command still works when pressing double `SHIFT` to open the command palette, but without the additional functionality the value of the plugin is limited. I've tried this on several different PC's running Windows with no change in the issue.

I know the live preview might not have even been out when Doubleshift was released last (in April), but even when live preview mode is disabled it doesn't work. Anyway, thanks in advance for any fix. If I were more familiar with TypeScript/JavaScript and the Obsidian API I'd be happy to look into it myself, and I did, indeed, fork the repository to have a look, but I'm having little luck in fixing it. It's an amazingly awesome plugin and I'm hoping it will be fixed if I am unable to do so myself.

There really isn't anything to add, but if any additional information is needed, please ask and I'll provide it. Have a good day! 👋

**Comment by Qwyntex** [comment]
Hi, thank you for the kind words. Weirdly I am not having any of the problems described on any of my systems. Could you tell me which version of obsidian you are using? (Settings/About)

**Comment by ghost** [comment]
My apologies, Qwyntex. After extensive testing with different vaults, plugins and settings, I realized I was wrong about several things. It turns out that, at least in my experience:

1. It works completely fine in new vaults.
2. It works completely fine with other settings changed, as well as with other plugins enabled.

The only case where I have trouble is when I install the plugin [Better Command Palette](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Plugins/obsidian-better-command-palette). It doesn't matter if the alternative command palette is installed or even enabled. **Your** plugin still works fine. The only problem is when the *core plugin* **"Command Palette"** is disabled. Doubleshift even works fine when *both* command palette plugins are enabled and in use, but if *only* the community plugin ("Better Command Palette") is enabled, or if—for **any** reason—the core plugin *Command Palette* is disabled, Doubleshift will present the strange behavior.

I don't know if you feel like trying it out to reproduce the "bug", because technically it's not *your* bug; it's a bug dealing with either the core plugin *Command Palette* or the community plugin *Better Command Palette*. My personal feeling is that it is the fault of the core plugin, because the issue only occurs when the former isn't enabled, whether the latter is enabled or not. Maybe it's not even possible to fix due to the way the API works, or maybe the core plugin needs to be fixed? I'm not familiar enough with JavaScript to do so or I'd look into it more.

But I *would* like to bring it to your attention, if only so you don't think that *your* code has an unresolved issue. I apologize once again for being so quick to blame your plugin, as well as for mis-reporting the conditions in which the issue can be reproduced. I hope you have a great day, and that I didn't cost you any worries. :wink:

Yours most sincerely,
    -Jackphrost (aka frostbyte/Sean S.)

**Comment by ghost** [comment]
P.S. Forgive me for commenting yet again, but I forgot to let you know that I appreciate you getting back to me right away, especially after it took me a few days to get back to *you*. :smile:

**Comment by Qwyntex** [comment]
No problem. I would rather have users that submit issues that turn out to be unnecessary than users that wont bring actual bugs to my attention and be annoyed about them. As for the weird behavior if a plugin isn't enabled i will fix that.
thank you.

**Comment by ghost** [comment]
You are awesome. Thank you, Qwyntex. I'm glad to know there are devs like you! :smile: 👍
